const express = require('express');
const handlebars = require('express-handlebars');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const session = require('express-session');
const passport = require('passport');
const methodOverride = require('method-override');

module.exports = app => {
    app.engine('.hbs', handlebars({
        defaultLayout: 'main',
        extname: '.hbs'
    }));

    app.use(cookieParser());                           //going from here if there is a logged in user, all the user information about req is hooked
    app.use(bodyParser.urlencoded({extended: true}));
    app.use(session({                               //sets a password when generating a session (ensuring that only sessions generated by our server are valid)
        secret: '123456',
        resave: false,
        saveUninitialized: false
    }));
    app.use(passport.initialize());
    app.use(passport.session());
    app.use(methodOverride("_method"));
    app.use((req, res, next) => {
        if (req.user) {
            res.locals.currentUser = req.user;    //we create a res.locals variable (currentUser) that comes from express and is accessible everywhere, we can call it halfway through handlebars in the template.
        }
        next();
    });

    app.set('view engine', '.hbs');

    app.use(express.static('./static'));
};